In [76]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [77]:
dataset=pd.read_csv("CKD.csv")

In [78]:
dataset.head(10)


age         bp sg   al   su       rbc        pc         pcc          ba  \
0  2.0  76.459948  c  3.0  0.0    normal  abnormal  notpresent  notpresent   
1  3.0  76.459948  c  2.0  0.0    normal    normal  notpresent  notpresent   
2  4.0  76.459948  a  1.0  0.0    normal    normal  notpresent  notpresent   
3  5.0  76.459948  d  1.0  0.0    normal    normal  notpresent  notpresent   
4  5.0  50.000000  c  0.0  0.0    normal    normal  notpresent  notpresent   
5  6.0  60.000000  c  4.0  0.0  abnormal  abnormal  notpresent     present   
6  7.0  50.000000  a  4.0  0.0    normal    normal  notpresent  notpresent   
7  8.0  60.000000  b  3.0  0.0    normal    normal  notpresent  notpresent   
8  8.0  50.000000  a  4.0  0.0    normal    normal  notpresent  notpresent   
9  8.0  76.459948  a  0.0  0.0    normal    normal  notpresent  notpresent   

          bgr  ...        pcv            wc        rc  htn  dm  cad  appet  \
0  148.112676  ...  38.868902   8408.191126  4.705597   no  no   no    yes   
1  148.112676  ...  34.000000  12300.000000  4.705597   no  no   no    yes   
2   99.000000  ...  34.000000   8408.191126  4.705597   no  no   no    yes   
3  148.112676  ...  38.868902   8408.191126  4.705597   no  no   no    yes   
4  148.112676  ...  36.000000  12400.000000  4.705597   no  no   no    yes   
5   94.000000  ...  30.000000  16700.000000  4.800000   no  no   no   poor   
6  148.112676  ...  38.000000   6000.000000  4.705597   no  no   no    yes   
7   78.000000  ...  41.000000   6700.000000  4.705597   no  no   no   poor   
8  148.112676  ...  38.868902   8408.191126  4.705597   no  no   no    yes   
9   80.000000  ...  38.000000   8408.191126  4.705597   no  no   no    yes   

     pe  ane classification  
0   yes   no            yes  
1  poor   no            yes  
2  poor   no            yes  
3  poor  yes            yes  
4  poor   no            yes  
5  poor   no            yes  
6  poor   no            yes  
7   yes   no            yes  
8   yes   no            yes  
9  poor   no            yes  

[10 rows x 25 columns]

In [79]:
dataset.shape

(399, 25)

In [80]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [81]:
dataset.shape

(399, 28)

In [82]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 399 entries, 0 to 398
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   age                 399 non-null    float64
 1   bp                  399 non-null    float64
 2   al                  399 non-null    float64
 3   su                  399 non-null    float64
 4   bgr                 399 non-null    float64
 5   bu                  399 non-null    float64
 6   sc                  399 non-null    float64
 7   sod                 399 non-null    float64
 8   pot                 399 non-null    float64
 9   hrmo                399 non-null    float64
 10  pcv                 399 non-null    float64
 11  wc                  399 non-null    float64
 12  rc                  399 non-null    float64
 13  sg_b                399 non-null    int64  
 14  sg_c                399 non-null    int64  
 15  sg_d                399 non-null    int64  
 16  sg_e    

In [83]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [84]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [85]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [86]:
dependent=dataset[['classification_yes']].values.ravel()

In [87]:
dependent

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [88]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size = 1/3, random_state = 0)

In [108]:
#from sklearn.linear_model import LogisticRegression
#classifier=LogisticRegression(random_state=0)
#classifier.fit(X_train, y_train)

In [109]:
#y_pred = classifier.predict(X_test)

In [110]:
#from sklearn.metrics import confusion_matrix
#cm = confusion_matrix(y_test, y_pred)

In [111]:
#print(cm)

In [112]:
#from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)

In [107]:
#print(clf_report)

In [89]:
#STANDARDISATION
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [91]:
X_train

array([[ 0.48681432,  1.79924415, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       [ 0.30305399,  0.26080096, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       [-0.61574769, -0.50842064, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       ...,
       [-0.43198735,  0.26080096, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       [-1.35078903,  0.26080096, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       [-0.06446668, -1.27764223, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456]], shape=(266, 27))

In [92]:
from sklearn.linear_model import LogisticRegression

In [93]:
from sklearn.model_selection import GridSearchCV

param_grid = {'solver':['newton-cg', 'lbfgs', 'liblinear', 'saga'],
             'penalty':['l2']} 



grid = GridSearchCV(LogisticRegression(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train, y_train) 

Fitting 5 folds for each of 4 candidates, totalling 20 fits


GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'penalty': ['l2'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'saga']},
             scoring='f1_weighted', verbose=3)

In [94]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)




In [95]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'penalty': 'l2', 'solver': 'newton-cg'}: 0.9924946382275899


In [96]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[51  0]
 [ 1 81]]


In [97]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133



In [98]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

1.0

In [99]:
table=pd.DataFrame.from_dict(re)

In [100]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_penalty  \
0       0.010985      0.005641         0.005492        0.001544            l2   
1       0.013155      0.003642         0.008038        0.000957            l2   
2       0.007555      0.004823         0.005486        0.001781            l2   
3       0.017056      0.004856         0.002621        0.000869            l2   

  param_solver                                    params  split0_test_score  \
0    newton-cg  {'penalty': 'l2', 'solver': 'newton-cg'}           0.981569   
1        lbfgs      {'penalty': 'l2', 'solver': 'lbfgs'}           0.981569   
2    liblinear  {'penalty': 'l2', 'solver': 'liblinear'}           0.963284   
3         saga       {'penalty': 'l2', 'solver': 'saga'}           0.981569   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.981014           0.981217           1.000000           1.000000   
1           0.981014           0.981217           1.000000           1.000000   
2           0.981233           0.962573           0.981217           0.981217   
3           0.981233           0.981217           0.981217           0.981217   

   mean_test_score  std_test_score  rank_test_score  
0         0.988760        0.009179                1  
1         0.988760        0.009179                1  
2         0.973905        0.008965                4  
3         0.981291        0.000139                3

In [101]:
import pickle
filename="finalmodel_linear.sav"

In [102]:
pickle.dump(grid,open(filename,'wb'))

In [103]:
preinput=sc.transform([[2.0,76.459948,3.0,0.0,0,1,0,0,148.112676,38.868902,8408.191126,4.705597,0,0,0,1,1,0,0,1,1,1,0,0,1,0,1]])

C:\Users\Jayasudha Kalamegam\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [104]:
preinput

array([[-3.06588549e+00, -1.15074877e-02,  1.75234707e+00,
        -3.64096372e-01, -1.96101988e+00, -1.12118037e+00,
        -5.39401918e-01, -1.30631566e+01,  6.45019642e+01,
         9.76186205e+00,  1.03017836e+03, -3.46297682e+00,
        -5.72763165e+00, -4.92940822e-01, -5.45491499e-01,
         2.21610269e+00,  7.22495675e+00, -2.56904652e+00,
        -1.95866374e+00,  2.91547595e+00,  4.24264069e+00,
         1.35269628e+00, -7.39264248e-01, -2.92770022e-01,
         5.16397779e-01, -5.22232968e-01,  2.24620893e+00]])

In [105]:
loaded_model=pickle.load(open("finalmodel_linear.sav",'rb'))
result=loaded_model.predict(preinput)

In [106]:
result

array([0])